### ISSUE TITLE
Replicating paper results for IIC using the restopt command-line jar

### ISSUE THREAD

**Issue by jequihua** [dimitri-justeau/cote-oubliee-choco-reserve-code#1]
First of all thank you so much for the great and replicable paper!

I'm trying to replicate the results for the IIC optimization using the command-line you provide but get a somewhat different spatial pattern. I'm using this command:

java -jar restopt.jar -objective IIC -habitat habitat.tif -accessible accessible.tif -restorable restorable.tif -cellArea 23 -accessibleValue 2 -maxDiam 6 -minRestore 90 -maxRestore 110 -minProportion 0.7 -precision 3 -o ./resultsiic

And obtain this final result:

![image](https://user-images.githubusercontent.com/5040621/232229460-e0a3ba32-6a03-43b6-92d4-75b9554e8844.png)

I wanted to know if I could change anything in the command to obtain the result in the paper exactly.

Thank you in advanced!

**Comment by dimitri-justeau** [comment]
Hello,

Sorry for the late response, I was out of the office. Thank you for your interest in restopt ! Actually, in this problem there are several optimal solutions, with different spatial arrangements, but in the end the optimal value is the same. This first command-line tool only offered basic features and did not include an option to output several optimal solutions.

Instead, the code used to generate the article's result is located here: https://github.com/dimitri-justeau/cote-oubliee-choco-reserve-code/tree/master/src/main/java/solve

Also, we recently developed an improved version of this program, with a performance enhancement and new features. The core is still in Java, but we released a user-friendly R package with preprocessing tools: https://github.com/dimitri-justeau/rflsgen

Let me know if you have any other question / issue !
